name: Docker Image CI

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag"
        required: true
        default: "main"

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Get version
        id: get_version
        run: |
          if ${{ startsWith(github.ref, 'refs/tags/') }}; then
            echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
          else
            echo ::set-output name=VERSION::${{ github.event.inputs.tag }}
          fi

      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Build Frontend
        run: cd frontend && pnpm i && pnpm build

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.actor }}/${{ github.repository }}:${{ steps.get_version.outputs.VERSION }}
            ${{ env.REGISTRY }}/${{ github.actor }}/${{ github.repository }}:latest
